on_fire = [fire_1,true,1200,20,0.1,true,false] spawn compile preprocessFile "Scripts\fire.sqf";
          [fire_2,true,1200,20,0.1,true,false] spawn compile preprocessFile "Scripts\fire.sqf";
          [fire_3,true,1200,20,0.1,true,false] spawn compile preprocessFile "Scripts\fire.sqf";
          [fire_4,true,1200,20,0.1,true,false] spawn compile preprocessFile "Scripts\fire.sqf";
          [fire_5,true,1200,20,0.1,true,false] spawn compile preprocessFile "Scripts\fire.sqf";
          [fire_6,true,1200,20,0.1,true,false] spawn compile preprocessFile "Scripts\fire.sqf";
          [fire_7,true,1200,20,0.1,true,false] spawn compile preprocessFile "Scripts\fire.sqf";
          [fire_8,true,1200,20,0.1,true,false] spawn compile preprocessFile "Scripts\fire.sqf";
          [fire_9,true,1200,20,0.1,true,false] spawn compile preprocessFile "Scripts\fire.sqf";
          [fire_10,true,1200,20,0.1,true,false] spawn compile preprocessFile "Scripts\fire.sqf";
          [fire_11,true,1200,20,0.1,true,false] spawn compile preprocessFile "Scripts\fire.sqf";
